apiVersion: v1
kind: Service
metadata:
  name: bubble-dev-service
  labels:
    app: bubble-dev
spec:
  type: LoadBalancer
  loadBalancerIP: 10.24.24.117
  externalIPs:
  - 10.24.24.117
  ports:
  - name: http
    port: 83 #local out port
    protocol: TCP
    targetPort: 83 # container port
  selector:
    app: bubble-dev #find all pod with app name
  sessionAffinity: None
