apiVersion: v1
kind: Service
metadata:
  name: bubble-prod-service
  labels:
    app: bubble-prod
spec:
  type: LoadBalancer
  loadBalancerIP: 10.24.24.117
  externalIPs:
  - 10.24.24.117
  ports:
  - name: http
    port: 81 #local out port
    protocol: TCP
    targetPort: 81 # container port
  selector:
    app: bubble-prod #find all pod with app name
  sessionAffinity: None
