apiVersion: apps/v1
kind: Deployment
metadata:
  name: bubble-stage-deployment
  namespace: bubble-stage
  labels:
    app: bubble-stage
spec:
  selector:
    matchLabels:
      app: bubble-stage
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bubble-stage
    spec:
      containers:
      - name: bubble-stage
        image: vincentbuiwork/bubble:stage
        imagePullPolicy: Always
        resources:
          requests:
            memory: 500M
          limits:
            memory: 1.5Gi
        livenessProbe:
          tcpSocket:
            port: 82
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 82
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort: 82
      restartPolicy: Always
